### ISSUE TITLE
consider moving devicesim in it's own repo under onosproject/

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#278]
leaner code and dependencies

**Comment by SeanCondon** [comment]
See also #273 - we've also go to decide if we want it to be gNMI only or with gNOI or others.
My own opinion on this is that there's scope for a gNMI only simulator. It will be important as we go on to have a variety of simulator types, with different capabilities.
So what I'm saying is that I don't see any need to burden the devicesim with gNOI or try to be a universal simulator.

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 
+1 I agree because the code is becoming big and it is not possible to put everything one package anymore. I reorganized the code but if we decide to move to its own repo, I can help with that. 

@SeanCondon 
+1 At this point, it makes sense to separate simulators from each other because each of the gNMI and gNOI is big enough. In future, when we start working on gNOI, we can have a separate simulator for that. Just my two cents.

**Comment by Andrea-Campanella** [comment]
Closing because the simulator has been moved.
