### ISSUE TITLE
Replace klog in the onos-config project with either standard log package or something better

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-config#324]
onos-config and its associated client programs use a combination of the following, each with their own benefits and drawbacks:

- klog (requires some k8s dependencies. Output is not seen on stdout or stderr. Log levels are configurable)

- standard log (from https://golang.org/pkg/log/, so no extra dependencies. Does not have levels of logging other than Print of Fatal. Works with k8s and stdout and stderr. Doesn't colour red for error)

- glog (from https://github.com/golang/glog. Has Info, Warning etc. Prints to stdout and stderr and works with k8s)

- fmt.println (standard go package. Should only be used in client programs for output to stdout

We should try to harmonize on one approach for logging, and make sure fmt.print line follows the given approach

**Comment by tomikazi** [comment]
My preference would be to figure out where the klog output goes; perhaps it is just a small config issue. If we can figure it out easily, then we can take advantage of the concise Info/Warn/Error/Debug log levels in a concise manner.

**Comment by kuujo** [comment]
I think the problem is just that we're not configuring klog when initializing commands. But FWIW I don't think klog is a necessity. It's an extension of glog built by Kubernetes to support more granular log levels, but I do see basically all the logging frameworks used throughout the k8s ecosystem.

But we _do_ see klog output when running onos-config in k8s.

**Comment by kuujo** [comment]
I just added klog to the Atomix test project and just had to do: `klog.SetOutput(os.Stdout)` in an `init()` function to enable logging.
