### ISSUE TITLE
Renaming of tags to make them more general for testing purposes 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#618]
**Is your feature request related to a problem? Please describe.**
We are adding a feature in onit that users can deploy an image with a specific tag. The users should be able to build images based on a given tag that can be passed as an argument to the make program. 

**Describe the solution you'd like**
We propose three tags to replace the app specific tags (i.e. starts with ONOS_...) that are defined in the makefile now as follows:
```
IMAGE_TAG (default will be latest)
BUILD_IMAGE_TAG (default will be release)
DEBUG_IMAGE_TAG (default will be debug)
```
Typically, users change DEBUG_IMAGE_TAG when they want to deploy a debug image in a cluster.

**Comment by kuujo** [comment]
The goal is to make the environment variables consistent across repos so a user can build an image with a specific tag to be pushed to the shared Docker registry for testing.

Of course, we _could_ leave this up to the user, in which case they just have to `docker tag onosproject/onos-config:debug onosproject/onos-config:jordan`. 

But ugh... @adibrastegarnia I just realized something. In order to push to the private registry, the image names also have to be prefixed with the registry IP, so as it is currently the user will have to `docker tag` the generated image regardless.

So, should we leave it up to the user to re-tag the image? Or should we fix this to ensure the user can generate an image suitable for the shared registry via `make`?

**Comment by adibrastegarnia** [comment]
@kuujo 
Should we close this or should we address it?
