### ISSUE TITLE
Evaluate Need for Description in changes and reintroduce

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#837]
**Is your feature request related to a problem? Please describe.**
Currently the description is not part of network or device changes as it has been removed from the Proto file. Please see line Line 231 or manager.go with //TODO lost description of Change reintroduce ?

**Describe the solution you'd like**
Evaluate the need for a description and if decided that we need one reintroduce it in the .proto file and set it in manager.go

**Describe alternatives you've considered**
do without change(s) description.

**Comment by SeanCondon** [comment]
I think with `Network Changes` there is a case to have a description field, but not on `Device Change`, because users do not address these individually (except through a `Network Change`).

This is from a usability perspective (which is subjective, and fairly low on our priority list ATM). The thing with fields like description is that it may not be enough for everybody, and where do you stop?
