### ISSUE TITLE
Unit tests that check for duplicate gNMI value changes never see an error

### ISSUE THREAD

**Issue by ray-milkey** [onosproject/onos-config#847]
**Describe the bug**
Setting a gnmi path to the same value it already has is no longer detected as an error. There are two unit tests that are currently skipped because of this. See
https://github.com/onosproject/onos-config/blob/4777e6469a9d8b62901d5d8568a941e1b66751e1/pkg/northbound/gnmi/set_test.go#L354
and
https://github.com/onosproject/onos-config/blob/4777e6469a9d8b62901d5d8568a941e1b66751e1/pkg/northbound/gnmi/set_test.go#L408

**Expected behavior**
The previous network changes store implementation did not allow duplicate entries.

**Comment by SeanCondon** [comment]
As before, the idea here is to prevent a user accidentally or otherwise to repeat the same network change - one just after the other (by the same I mean an identical set of paths for an identical set of devices).

If some other change happened in between (to the devices involved in this new network change) then it's OK to accept a change that had been given before.

The idea is that is there is **no change** to the config then the system should not list it as a change and should reject it. This is mainly coming from a usability perspective. 

The previous solution had an ordered set of network changes and it was easy to figure out what was in the config, just by looking at the network changes.

With the new implementation maybe a better way would be to **extract the current config** and if the new Network Change would make no difference (or the delta == 0) then do not accept the change. This could be done alongside validation, and works in a very similar way.

**Comment by ray-milkey** [comment]
I would favor an implementation that supports idempotency for operations. If an API call says "make the system state like this" and that is the existing state, that should be an OK thing in my view.

**Comment by SeanCondon** [comment]
Decision at Standup meeting on 4 Nov 19 was not to raise an error for this.
We might come back to it as an optimization in the future, but there is not a concrete reason to do so at the moment.

Also this means that there will be no check for duplicate names for Network Changes. 2 changes could have the same name - while this will not break the system - it could be confusing for users, but the same argument applies

**Comment by Andrea-Campanella** [comment]
Closing since decision was taken

**Comment by ray-milkey** [comment]
We decided to leave this open as a possible enhancement.
