### ISSUE TITLE
Improve comments in protobuf files

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/onos-config#882]
To generate better docs out of protobuf files, the comments in protobuf files should be improved. For example, some of the fields don't have comments yet and they don't show up in the generated docs.

**Comment by SeanCondon** [comment]
Some of the problem here is cross reference between sections 

For example in the "ListNetworkChangeResponse" section of the page:
https://docs.onosproject.org/onos-config/docs/api/diags/#onos.config.diags.ListNetworkChangeResponse
there is a link to NetworkChange type which does not work as it only points to
https://docs.onosproject.org/onos-config/docs/api/diags/#onos.config.change.network.NetworkChange
(on the same page).

Instead it should refer to:
https://docs.onosproject.org/onos-config/docs/api/types_change_network/#networkchange

**Comment by SeanCondon** [comment]
I think this is referring to the types in `admin.proto` like `ReadOnlyPath`, `ReadOnlySubPath` etc.
