### ISSUE TITLE
Enable configuration get during device connection

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-config#917]
**Is your feature request related to a problem? Please describe.**
Currently there is no config synchronisation during device connection, meaning that `onos-config` ignores the configuration (if any) present on the device. 

**Describe the solution you'd like**
`onos-config` should be capable of synchronising the config based on the user desire.
Each device needs the addition of a mode field.
A mode can be:
- `force` for onos-config total control, meaning ignoring the device configuration and just push what onos has. 
- `blend` to push the configuration onos-config has and incorporate the devices for attributes not set in `onos-config` 
- `passive` to get every config the device has and override the internal config for that parameter while also pushing the ones for which he device had no value. 

This `mode` parameter should come from `onos-topo`.

**Additional context**
Please see #916

**Comment by SeanCondon** [comment]
In the above I think `force` should be the default if `mode` is not specified in `onos-topo`. The idea is to remove the burden on someone adding the device to understand and remember what to specify each time a device needs to be created.

Additionally I think there is also scope for a per device **type and version** mode too which could be used to override this default.

This could be part of the model plugin definition `getDefaultInitSyncMode()` - so that on a per device type (and version) basis a plugin could define that a certain type of device the **default** would be:
a) `force` (the default)
b) `blend`
c) `passive`

The benefit would be that some device types might always require a certain mode, and it would save the user having to remember to set the mode.

This could be overridden by setting the mode on a per device basis in `topo` as initially suggested above.

The downside of an extra parameter like this is the extra testing involved in validating that it works right.

**Comment by Andrea-Campanella** [comment]
Adding additional information after a discussion with @SeanCondon 
Mode:

- force we do set from onos-config with no check on the device related to those attributes and purge the other attributes that are present on the device but not in onos-config.
- blend we do set from onos-config for available parameters, get for ones onos-config does not but the devices has
- passive we do a get on the device for it's current config, save it in onos-config eventually over-writing existing parameter and purging attributes that are not set on the device.

This explanation overrides the issue original one.

**Comment by Andrea-Campanella** [comment]
Initial set done in #930
